name: pigeonholelive_sdk
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://pigeonholelive.com/
repository: https://github.com/lkloon123/pigeonholelive-dart-sdk

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: ^4.0.0
  get_it: ^6.0.0
  json_annotation: ^4.0.1

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  json_serializable: ^4.1.0
  build_runner: ^1.12.2
  coverage: ^1.0.2
  http_mock_adapter: ^0.2.1